# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cristina Silva
email: casilva62592@gmail.com
description: i make things
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cristinasilva.co" # the base hostname & protocol for your site
twitter_username: silvacristina_
github_username:  ohaicristina

# Build settings
markdown: kramdown
exclude: ["CNAME", "README.md"]
